# Application Configuration
Name = "test-api"
Port = 8000
Subdomain = "test-api" # Will be deployed to test-api.deploy-app.com

# Project Configuration
DockerfilePath = "Dockerfile" # Relative to ProjectPath
EnvFile = ".env"              # Relative to ProjectPath
ProjectPath = "."

# Resource Allocation
CPU = "100m"     # CPU cores (e.g., this is 0.1 cores)
Memory = "100Mi" # Memory allocation (e.g., "256Mi", "1Gi", "2Gi")

# Scaling Configuration
[Replicas]
Max = 2 # Maximum number of replicas
Min = 1 # Minimum number of replicas

# Autoscaling Triggers
[Scalers]
CPUTarget = 70    # CPU utilization target percentage
MemoryTarget = 80 # Memory utilization target percentage

# Health Checks
[Health]
Interval = 30    # Check interval in seconds
Path = "/health" # Health check endpoint
Timeout = 5      # Timeout in seconds

# Logging Configuration
[Logs]
RetentionPeriod = "7d" # Log retention period
Structured = true      # Enable structured JSON logging
