CPU = "100m"
DockerfilePath = "Dockerfile"
EnvFile = ".env"
Memory = "512Mi"
Name = "myapp"
Port = 8000
ProjectPath = "."
Subdomain = "myapp"

[Replicas]
Max = 1
Min = 1

[Scalers]
CPUTarget = 70
MemoryTarget = 0

[Health]
Interval = 30
Path = "/health"
Timeout = 5

[Logs]
RetentionPeriod = "7d"
Structured = true
