apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loco-ingress
  namespace: loco-setup
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web

spec:
  tls:
  - hosts:
      - deploy-app.com
    secretName: loco-tls
  rules:
  - host: deploy-app.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-world
            port:
              number: 80