apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: loco-api
    namespace: loco-system
spec:
    parentRefs:
        - name: eg
    hostnames:
        - "loco.deploy-app.com"
    rules:
        - backendRefs:
              - group: ""
                kind: Service
                name: loco-api
                port: 80
                weight: 1
          matches:
              - path:
                    type: PathPrefix
                    value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: loco-api-grpc
  namespace: loco-system
spec:
  parentRefs:
    - name: eg
  hostnames:
    - "loco.deploy-app.com"
  rules:
    - matches:
        - method:
            service: "proto.*"
            method: ".*"
            type: RegularExpression
        - method:
            service: "proto.registry.v1.RegistryService"
            method: ".*"
            type: RegularExpression
        - method:
            service: "proto.oauth.v1.OAuthService"
            method: ".*"
            type: RegularExpression
      backendRefs:
        - group: ""
          kind: Service
          name: loco-api
          port: 80
          weight: 1
