[Metadata]
ConfigVersion = "0.1"
Description = "Auth Service"
Name = "auth"

[Resources]
Cpu = "100m"
Memory = "256Mi"

[Resources.Replicas]
Max = 1
Min = 1

[Resources.Scalers]
CpuTarget = 70
Enabled = true

[Build]
DockerfilePath = "Dockerfile"
Type = "docker"

[Routing]
IdleTimeout = 60
PathPrefix = "/auth"
Port = 8000
Subdomain = "test-api"

[Health]
Interval = 30
Path = "/health"
StartupGracePeriod = 0
Timeout = 5

[Env]
File = ".env"

[Obs.Logging]
Enabled = true
RetentionPeriod = "7d"
Structured = false

[Obs.Metrics]
Enabled = false
Path = "/metrics"
Port = 9090

[Obs.Tracing]
Enabled = false
SampleRate = 0.1
