# deployment.yaml
mode: deployment

image:
    repository: otel/opentelemetry-collector-contrib
    tag: 0.138.0

# We only want one of these collectors - any more and we'd produce duplicate data
replicaCount: 1

presets:
    kubernetesAttributes:
        enabled: true
        # When enabled the processor will extra all labels for an associated pod and add them as resource attributes.
        # The label's exact name will be the key.
        extractAllPodLabels: true
        # When enabled the processor will extra all annotations for an associated pod and add them as resource attributes.
        # The annotation's exact name will be the key.
        extractAllPodAnnotations: true
    # Configures the collector to collect kubernetes events.
    # Adds the k8sobject receiver to the logs pipeline and collects kubernetes events by default.
    # More Info: https://opentelemetry.io/docs/kubernetes/collector/components/#kubernetes-objects-receiver
    kubernetesEvents:
        enabled: true
    # Configures the Kubernetes Cluster Receiver to collect cluster-level metrics.
    # Adds the k8s_cluster receiver to the metrics pipeline and adds the necessary rules to ClusteRole.
    # More Info: https://opentelemetry.io/docs/kubernetes/collector/components/#kubernetes-cluster-receiver
    clusterMetrics:
        enabled: true

config:
    exporters:
        clickhouse:
            endpoint: tcp://clickhouse-clickhouse.observability.svc.cluster.local:9000?dial_timeout=10s&compress=lz4&async_insert=1
            # ttl: 72h
            username: default
            password: ""
            traces_table_name: otel_traces
            logs_table_name: otel_logs
            create_schema: true
            timeout: 5s
            database: default
    service:
        pipelines:
            logs:
                exporters: [clickhouse]
            metrics:
                exporters: [clickhouse]
