// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: proto/app/v1/app.proto

package appv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- deploy app ---
type DeployAppRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LocoConfig     *LocoConfig            `protobuf:"bytes,1,opt,name=loco_config,json=locoConfig,proto3" json:"loco_config,omitempty"`
	ContainerImage string                 `protobuf:"bytes,2,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	EnvVars        []*EnvVar              `protobuf:"bytes,3,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeployAppRequest) Reset() {
	*x = DeployAppRequest{}
	mi := &file_proto_app_v1_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployAppRequest) ProtoMessage() {}

func (x *DeployAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployAppRequest.ProtoReflect.Descriptor instead.
func (*DeployAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{0}
}

func (x *DeployAppRequest) GetLocoConfig() *LocoConfig {
	if x != nil {
		return x.LocoConfig
	}
	return nil
}

func (x *DeployAppRequest) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

func (x *DeployAppRequest) GetEnvVars() []*EnvVar {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

type LocoConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port           int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Subdomain      string                 `protobuf:"bytes,3,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	DockerfilePath string                 `protobuf:"bytes,4,opt,name=dockerfile_path,json=dockerfilePath,proto3" json:"dockerfile_path,omitempty"`
	EnvFile        string                 `protobuf:"bytes,5,opt,name=env_file,json=envFile,proto3" json:"env_file,omitempty"`
	Cpu            string                 `protobuf:"bytes,6,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory         string                 `protobuf:"bytes,7,opt,name=memory,proto3" json:"memory,omitempty"`
	Replicas       *Replicas              `protobuf:"bytes,8,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Scalers        *Scalers               `protobuf:"bytes,9,opt,name=scalers,proto3" json:"scalers,omitempty"`
	Health         *Health                `protobuf:"bytes,10,opt,name=health,proto3" json:"health,omitempty"`
	Logs           *Logs                  `protobuf:"bytes,11,opt,name=logs,proto3" json:"logs,omitempty"`
	SchemaVersion  string                 `protobuf:"bytes,12,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocoConfig) Reset() {
	*x = LocoConfig{}
	mi := &file_proto_app_v1_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocoConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocoConfig) ProtoMessage() {}

func (x *LocoConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocoConfig.ProtoReflect.Descriptor instead.
func (*LocoConfig) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{1}
}

func (x *LocoConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LocoConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *LocoConfig) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *LocoConfig) GetDockerfilePath() string {
	if x != nil {
		return x.DockerfilePath
	}
	return ""
}

func (x *LocoConfig) GetEnvFile() string {
	if x != nil {
		return x.EnvFile
	}
	return ""
}

func (x *LocoConfig) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *LocoConfig) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *LocoConfig) GetReplicas() *Replicas {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *LocoConfig) GetScalers() *Scalers {
	if x != nil {
		return x.Scalers
	}
	return nil
}

func (x *LocoConfig) GetHealth() *Health {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *LocoConfig) GetLogs() *Logs {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *LocoConfig) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

type EnvVar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVar) Reset() {
	*x = EnvVar{}
	mi := &file_proto_app_v1_app_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVar) ProtoMessage() {}

func (x *EnvVar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVar.ProtoReflect.Descriptor instead.
func (*EnvVar) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{2}
}

func (x *EnvVar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvVar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Replicas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           int32                  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Replicas) Reset() {
	*x = Replicas{}
	mi := &file_proto_app_v1_app_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Replicas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replicas) ProtoMessage() {}

func (x *Replicas) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replicas.ProtoReflect.Descriptor instead.
func (*Replicas) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{3}
}

func (x *Replicas) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Replicas) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type Scalers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuTarget     int32                  `protobuf:"varint,1,opt,name=cpu_target,json=cpuTarget,proto3" json:"cpu_target,omitempty"`
	MemoryTarget  int32                  `protobuf:"varint,2,opt,name=memory_target,json=memoryTarget,proto3" json:"memory_target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scalers) Reset() {
	*x = Scalers{}
	mi := &file_proto_app_v1_app_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scalers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scalers) ProtoMessage() {}

func (x *Scalers) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scalers.ProtoReflect.Descriptor instead.
func (*Scalers) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{4}
}

func (x *Scalers) GetCpuTarget() int32 {
	if x != nil {
		return x.CpuTarget
	}
	return 0
}

func (x *Scalers) GetMemoryTarget() int32 {
	if x != nil {
		return x.MemoryTarget
	}
	return 0
}

type Health struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interval      int32                  `protobuf:"varint,1,opt,name=interval,proto3" json:"interval,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Timeout       int32                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Health) Reset() {
	*x = Health{}
	mi := &file_proto_app_v1_app_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Health) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Health) ProtoMessage() {}

func (x *Health) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Health.ProtoReflect.Descriptor instead.
func (*Health) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{5}
}

func (x *Health) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *Health) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Health) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type Logs struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RetentionPeriod string                 `protobuf:"bytes,1,opt,name=retention_period,json=retentionPeriod,proto3" json:"retention_period,omitempty"`
	Structured      bool                   `protobuf:"varint,2,opt,name=structured,proto3" json:"structured,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Logs) Reset() {
	*x = Logs{}
	mi := &file_proto_app_v1_app_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logs) ProtoMessage() {}

func (x *Logs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logs.ProtoReflect.Descriptor instead.
func (*Logs) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{6}
}

func (x *Logs) GetRetentionPeriod() string {
	if x != nil {
		return x.RetentionPeriod
	}
	return ""
}

func (x *Logs) GetStructured() bool {
	if x != nil {
		return x.Structured
	}
	return false
}

type DeployAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployAppResponse) Reset() {
	*x = DeployAppResponse{}
	mi := &file_proto_app_v1_app_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployAppResponse) ProtoMessage() {}

func (x *DeployAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployAppResponse.ProtoReflect.Descriptor instead.
func (*DeployAppResponse) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{7}
}

func (x *DeployAppResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Tail          int64                  `protobuf:"varint,2,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_proto_app_v1_app_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{8}
}

func (x *LogsRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *LogsRequest) GetTail() int64 {
	if x != nil {
		return x.Tail
	}
	return 0
}

type LogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PodName       string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Log           string                 `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	mi := &file_proto_app_v1_app_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{9}
}

func (x *LogsResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogsResponse) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *LogsResponse) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

// --- status ---
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_app_v1_app_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{10}
}

func (x *StatusRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type StatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Pods            int32                  `protobuf:"varint,2,opt,name=pods,proto3" json:"pods,omitempty"`
	CpuUsage        string                 `protobuf:"bytes,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage     string                 `protobuf:"bytes,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	Latency         string                 `protobuf:"bytes,5,opt,name=latency,proto3" json:"latency,omitempty"`
	Url             string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	DeployedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deployed_at,json=deployedAt,proto3" json:"deployed_at,omitempty"`
	DeployedBy      string                 `protobuf:"bytes,8,opt,name=deployed_by,json=deployedBy,proto3" json:"deployed_by,omitempty"`
	Tls             string                 `protobuf:"bytes,9,opt,name=tls,proto3" json:"tls,omitempty"`
	Health          string                 `protobuf:"bytes,10,opt,name=health,proto3" json:"health,omitempty"`
	Autoscaling     bool                   `protobuf:"varint,11,opt,name=autoscaling,proto3" json:"autoscaling,omitempty"`
	MinReplicas     int32                  `protobuf:"varint,12,opt,name=min_replicas,json=minReplicas,proto3" json:"min_replicas,omitempty"`
	MaxReplicas     int32                  `protobuf:"varint,13,opt,name=max_replicas,json=maxReplicas,proto3" json:"max_replicas,omitempty"`
	DesiredReplicas int32                  `protobuf:"varint,14,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`
	ReadyReplicas   int32                  `protobuf:"varint,15,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_app_v1_app_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{11}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetPods() int32 {
	if x != nil {
		return x.Pods
	}
	return 0
}

func (x *StatusResponse) GetCpuUsage() string {
	if x != nil {
		return x.CpuUsage
	}
	return ""
}

func (x *StatusResponse) GetMemoryUsage() string {
	if x != nil {
		return x.MemoryUsage
	}
	return ""
}

func (x *StatusResponse) GetLatency() string {
	if x != nil {
		return x.Latency
	}
	return ""
}

func (x *StatusResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *StatusResponse) GetDeployedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeployedAt
	}
	return nil
}

func (x *StatusResponse) GetDeployedBy() string {
	if x != nil {
		return x.DeployedBy
	}
	return ""
}

func (x *StatusResponse) GetTls() string {
	if x != nil {
		return x.Tls
	}
	return ""
}

func (x *StatusResponse) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *StatusResponse) GetAutoscaling() bool {
	if x != nil {
		return x.Autoscaling
	}
	return false
}

func (x *StatusResponse) GetMinReplicas() int32 {
	if x != nil {
		return x.MinReplicas
	}
	return 0
}

func (x *StatusResponse) GetMaxReplicas() int32 {
	if x != nil {
		return x.MaxReplicas
	}
	return 0
}

func (x *StatusResponse) GetDesiredReplicas() int32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

func (x *StatusResponse) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

var File_proto_app_v1_app_proto protoreflect.FileDescriptor

const file_proto_app_v1_app_proto_rawDesc = "" +
	"\n" +
	"\x16proto/app/v1/app.proto\x12\fproto.app.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa7\x01\n" +
	"\x10DeployAppRequest\x129\n" +
	"\vloco_config\x18\x01 \x01(\v2\x18.proto.app.v1.LocoConfigR\n" +
	"locoConfig\x12'\n" +
	"\x0fcontainer_image\x18\x02 \x01(\tR\x0econtainerImage\x12/\n" +
	"\benv_vars\x18\x03 \x03(\v2\x14.proto.app.v1.EnvVarR\aenvVars\"\xa2\x03\n" +
	"\n" +
	"LocoConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1c\n" +
	"\tsubdomain\x18\x03 \x01(\tR\tsubdomain\x12'\n" +
	"\x0fdockerfile_path\x18\x04 \x01(\tR\x0edockerfilePath\x12\x19\n" +
	"\benv_file\x18\x05 \x01(\tR\aenvFile\x12\x10\n" +
	"\x03cpu\x18\x06 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\a \x01(\tR\x06memory\x122\n" +
	"\breplicas\x18\b \x01(\v2\x16.proto.app.v1.ReplicasR\breplicas\x12/\n" +
	"\ascalers\x18\t \x01(\v2\x15.proto.app.v1.ScalersR\ascalers\x12,\n" +
	"\x06health\x18\n" +
	" \x01(\v2\x14.proto.app.v1.HealthR\x06health\x12&\n" +
	"\x04logs\x18\v \x01(\v2\x12.proto.app.v1.LogsR\x04logs\x12%\n" +
	"\x0eschema_version\x18\f \x01(\tR\rschemaVersion\"2\n" +
	"\x06EnvVar\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\".\n" +
	"\bReplicas\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x05R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\"M\n" +
	"\aScalers\x12\x1d\n" +
	"\n" +
	"cpu_target\x18\x01 \x01(\x05R\tcpuTarget\x12#\n" +
	"\rmemory_target\x18\x02 \x01(\x05R\fmemoryTarget\"R\n" +
	"\x06Health\x12\x1a\n" +
	"\binterval\x18\x01 \x01(\x05R\binterval\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x05R\atimeout\"Q\n" +
	"\x04Logs\x12)\n" +
	"\x10retention_period\x18\x01 \x01(\tR\x0fretentionPeriod\x12\x1e\n" +
	"\n" +
	"structured\x18\x02 \x01(\bR\n" +
	"structured\"-\n" +
	"\x11DeployAppResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"<\n" +
	"\vLogsRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x12\n" +
	"\x04tail\x18\x02 \x01(\x03R\x04tail\"u\n" +
	"\fLogsResponse\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x10\n" +
	"\x03log\x18\x03 \x01(\tR\x03log\"*\n" +
	"\rStatusRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\"\xea\x03\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04pods\x18\x02 \x01(\x05R\x04pods\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\tR\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x04 \x01(\tR\vmemoryUsage\x12\x18\n" +
	"\alatency\x18\x05 \x01(\tR\alatency\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12;\n" +
	"\vdeployed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deployedAt\x12\x1f\n" +
	"\vdeployed_by\x18\b \x01(\tR\n" +
	"deployedBy\x12\x10\n" +
	"\x03tls\x18\t \x01(\tR\x03tls\x12\x16\n" +
	"\x06health\x18\n" +
	" \x01(\tR\x06health\x12 \n" +
	"\vautoscaling\x18\v \x01(\bR\vautoscaling\x12!\n" +
	"\fmin_replicas\x18\f \x01(\x05R\vminReplicas\x12!\n" +
	"\fmax_replicas\x18\r \x01(\x05R\vmaxReplicas\x12)\n" +
	"\x10desired_replicas\x18\x0e \x01(\x05R\x0fdesiredReplicas\x12%\n" +
	"\x0eready_replicas\x18\x0f \x01(\x05R\rreadyReplicas2\xe6\x01\n" +
	"\n" +
	"AppService\x12N\n" +
	"\tDeployApp\x12\x1e.proto.app.v1.DeployAppRequest\x1a\x1f.proto.app.v1.DeployAppResponse\"\x00\x12A\n" +
	"\x04Logs\x12\x19.proto.app.v1.LogsRequest\x1a\x1a.proto.app.v1.LogsResponse\"\x000\x01\x12E\n" +
	"\x06Status\x12\x1b.proto.app.v1.StatusRequest\x1a\x1c.proto.app.v1.StatusResponse\"\x00B0Z.github.com/nikumar1206/loco/proto/app/v1;appv1b\x06proto3"

var (
	file_proto_app_v1_app_proto_rawDescOnce sync.Once
	file_proto_app_v1_app_proto_rawDescData []byte
)

func file_proto_app_v1_app_proto_rawDescGZIP() []byte {
	file_proto_app_v1_app_proto_rawDescOnce.Do(func() {
		file_proto_app_v1_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_app_v1_app_proto_rawDesc), len(file_proto_app_v1_app_proto_rawDesc)))
	})
	return file_proto_app_v1_app_proto_rawDescData
}

var file_proto_app_v1_app_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_app_v1_app_proto_goTypes = []any{
	(*DeployAppRequest)(nil),      // 0: proto.app.v1.DeployAppRequest
	(*LocoConfig)(nil),            // 1: proto.app.v1.LocoConfig
	(*EnvVar)(nil),                // 2: proto.app.v1.EnvVar
	(*Replicas)(nil),              // 3: proto.app.v1.Replicas
	(*Scalers)(nil),               // 4: proto.app.v1.Scalers
	(*Health)(nil),                // 5: proto.app.v1.Health
	(*Logs)(nil),                  // 6: proto.app.v1.Logs
	(*DeployAppResponse)(nil),     // 7: proto.app.v1.DeployAppResponse
	(*LogsRequest)(nil),           // 8: proto.app.v1.LogsRequest
	(*LogsResponse)(nil),          // 9: proto.app.v1.LogsResponse
	(*StatusRequest)(nil),         // 10: proto.app.v1.StatusRequest
	(*StatusResponse)(nil),        // 11: proto.app.v1.StatusResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_proto_app_v1_app_proto_depIdxs = []int32{
	1,  // 0: proto.app.v1.DeployAppRequest.loco_config:type_name -> proto.app.v1.LocoConfig
	2,  // 1: proto.app.v1.DeployAppRequest.env_vars:type_name -> proto.app.v1.EnvVar
	3,  // 2: proto.app.v1.LocoConfig.replicas:type_name -> proto.app.v1.Replicas
	4,  // 3: proto.app.v1.LocoConfig.scalers:type_name -> proto.app.v1.Scalers
	5,  // 4: proto.app.v1.LocoConfig.health:type_name -> proto.app.v1.Health
	6,  // 5: proto.app.v1.LocoConfig.logs:type_name -> proto.app.v1.Logs
	12, // 6: proto.app.v1.LogsResponse.timestamp:type_name -> google.protobuf.Timestamp
	12, // 7: proto.app.v1.StatusResponse.deployed_at:type_name -> google.protobuf.Timestamp
	0,  // 8: proto.app.v1.AppService.DeployApp:input_type -> proto.app.v1.DeployAppRequest
	8,  // 9: proto.app.v1.AppService.Logs:input_type -> proto.app.v1.LogsRequest
	10, // 10: proto.app.v1.AppService.Status:input_type -> proto.app.v1.StatusRequest
	7,  // 11: proto.app.v1.AppService.DeployApp:output_type -> proto.app.v1.DeployAppResponse
	9,  // 12: proto.app.v1.AppService.Logs:output_type -> proto.app.v1.LogsResponse
	11, // 13: proto.app.v1.AppService.Status:output_type -> proto.app.v1.StatusResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_app_v1_app_proto_init() }
func file_proto_app_v1_app_proto_init() {
	if File_proto_app_v1_app_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_app_v1_app_proto_rawDesc), len(file_proto_app_v1_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_app_v1_app_proto_goTypes,
		DependencyIndexes: file_proto_app_v1_app_proto_depIdxs,
		MessageInfos:      file_proto_app_v1_app_proto_msgTypes,
	}.Build()
	File_proto_app_v1_app_proto = out.File
	file_proto_app_v1_app_proto_goTypes = nil
	file_proto_app_v1_app_proto_depIdxs = nil
}
