// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: proto/app/v1/app.proto

package appv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- deploy app ---
type DeployAppRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LocoConfig     *LocoConfig            `protobuf:"bytes,1,opt,name=loco_config,json=locoConfig,proto3" json:"loco_config,omitempty"`
	ContainerImage string                 `protobuf:"bytes,2,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	EnvVars        []*EnvVar              `protobuf:"bytes,3,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeployAppRequest) Reset() {
	*x = DeployAppRequest{}
	mi := &file_proto_app_v1_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployAppRequest) ProtoMessage() {}

func (x *DeployAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployAppRequest.ProtoReflect.Descriptor instead.
func (*DeployAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{0}
}

func (x *DeployAppRequest) GetLocoConfig() *LocoConfig {
	if x != nil {
		return x.LocoConfig
	}
	return nil
}

func (x *DeployAppRequest) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

func (x *DeployAppRequest) GetEnvVars() []*EnvVar {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

type LocoConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Resources     *Resources             `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	Build         *Build                 `protobuf:"bytes,3,opt,name=build,proto3" json:"build,omitempty"`
	Routing       *Routing               `protobuf:"bytes,4,opt,name=routing,proto3" json:"routing,omitempty"`
	Health        *HealthCheck           `protobuf:"bytes,5,opt,name=health,proto3" json:"health,omitempty"`
	Env           *Env                   `protobuf:"bytes,6,opt,name=env,proto3" json:"env,omitempty"`
	Obs           *Obs                   `protobuf:"bytes,7,opt,name=obs,proto3" json:"obs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocoConfig) Reset() {
	*x = LocoConfig{}
	mi := &file_proto_app_v1_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocoConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocoConfig) ProtoMessage() {}

func (x *LocoConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocoConfig.ProtoReflect.Descriptor instead.
func (*LocoConfig) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{1}
}

func (x *LocoConfig) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *LocoConfig) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *LocoConfig) GetBuild() *Build {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *LocoConfig) GetRouting() *Routing {
	if x != nil {
		return x.Routing
	}
	return nil
}

func (x *LocoConfig) GetHealth() *HealthCheck {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *LocoConfig) GetEnv() *Env {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *LocoConfig) GetObs() *Obs {
	if x != nil {
		return x.Obs
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion string                 `protobuf:"bytes,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_proto_app_v1_app_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *Metadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Replicas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Max           int32                  `protobuf:"varint,1,opt,name=max,proto3" json:"max,omitempty"`
	Min           int32                  `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Replicas) Reset() {
	*x = Replicas{}
	mi := &file_proto_app_v1_app_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Replicas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replicas) ProtoMessage() {}

func (x *Replicas) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replicas.ProtoReflect.Descriptor instead.
func (*Replicas) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{3}
}

func (x *Replicas) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *Replicas) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

type Scalers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuTarget     int32                  `protobuf:"varint,1,opt,name=cpu_target,json=cpuTarget,proto3" json:"cpu_target,omitempty"`
	MemoryTarget  int32                  `protobuf:"varint,2,opt,name=memory_target,json=memoryTarget,proto3" json:"memory_target,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scalers) Reset() {
	*x = Scalers{}
	mi := &file_proto_app_v1_app_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scalers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scalers) ProtoMessage() {}

func (x *Scalers) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scalers.ProtoReflect.Descriptor instead.
func (*Scalers) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{4}
}

func (x *Scalers) GetCpuTarget() int32 {
	if x != nil {
		return x.CpuTarget
	}
	return 0
}

func (x *Scalers) GetMemoryTarget() int32 {
	if x != nil {
		return x.MemoryTarget
	}
	return 0
}

func (x *Scalers) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           string                 `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Replicas      *Replicas              `protobuf:"bytes,3,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Scalers       *Scalers               `protobuf:"bytes,4,opt,name=scalers,proto3" json:"scalers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_proto_app_v1_app_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{5}
}

func (x *Resources) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *Resources) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *Resources) GetReplicas() *Replicas {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *Resources) GetScalers() *Scalers {
	if x != nil {
		return x.Scalers
	}
	return nil
}

type Build struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DockerfilePath string                 `protobuf:"bytes,1,opt,name=dockerfile_path,json=dockerfilePath,proto3" json:"dockerfile_path,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Build) Reset() {
	*x = Build{}
	mi := &file_proto_app_v1_app_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Build) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Build) ProtoMessage() {}

func (x *Build) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Build.ProtoReflect.Descriptor instead.
func (*Build) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{6}
}

func (x *Build) GetDockerfilePath() string {
	if x != nil {
		return x.DockerfilePath
	}
	return ""
}

func (x *Build) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Routing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdleTimeout   int32                  `protobuf:"varint,1,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
	PathPrefix    string                 `protobuf:"bytes,2,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Subdomain     string                 `protobuf:"bytes,4,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Routing) Reset() {
	*x = Routing{}
	mi := &file_proto_app_v1_app_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Routing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Routing) ProtoMessage() {}

func (x *Routing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Routing.ProtoReflect.Descriptor instead.
func (*Routing) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{7}
}

func (x *Routing) GetIdleTimeout() int32 {
	if x != nil {
		return x.IdleTimeout
	}
	return 0
}

func (x *Routing) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *Routing) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Routing) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

type HealthCheck struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Interval           int32                  `protobuf:"varint,1,opt,name=interval,proto3" json:"interval,omitempty"`
	Path               string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	StartupGracePeriod int32                  `protobuf:"varint,3,opt,name=startup_grace_period,json=startupGracePeriod,proto3" json:"startup_grace_period,omitempty"`
	Timeout            int32                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	FailThreshold      int32                  `protobuf:"varint,5,opt,name=fail_threshold,json=failThreshold,proto3" json:"fail_threshold,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_proto_app_v1_app_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheck) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *HealthCheck) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HealthCheck) GetStartupGracePeriod() int32 {
	if x != nil {
		return x.StartupGracePeriod
	}
	return 0
}

func (x *HealthCheck) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *HealthCheck) GetFailThreshold() int32 {
	if x != nil {
		return x.FailThreshold
	}
	return 0
}

type Env struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Variables     []*EnvVar              `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Env) Reset() {
	*x = Env{}
	mi := &file_proto_app_v1_app_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Env) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Env) ProtoMessage() {}

func (x *Env) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Env.ProtoReflect.Descriptor instead.
func (*Env) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{9}
}

func (x *Env) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Env) GetVariables() []*EnvVar {
	if x != nil {
		return x.Variables
	}
	return nil
}

type EnvVar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVar) Reset() {
	*x = EnvVar{}
	mi := &file_proto_app_v1_app_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVar) ProtoMessage() {}

func (x *EnvVar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVar.ProtoReflect.Descriptor instead.
func (*EnvVar) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{10}
}

func (x *EnvVar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvVar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Logging struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Enabled         bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	RetentionPeriod string                 `protobuf:"bytes,2,opt,name=retention_period,json=retentionPeriod,proto3" json:"retention_period,omitempty"`
	Structured      bool                   `protobuf:"varint,3,opt,name=structured,proto3" json:"structured,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Logging) Reset() {
	*x = Logging{}
	mi := &file_proto_app_v1_app_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logging) ProtoMessage() {}

func (x *Logging) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logging.ProtoReflect.Descriptor instead.
func (*Logging) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{11}
}

func (x *Logging) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Logging) GetRetentionPeriod() string {
	if x != nil {
		return x.RetentionPeriod
	}
	return ""
}

func (x *Logging) GetStructured() bool {
	if x != nil {
		return x.Structured
	}
	return false
}

type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_proto_app_v1_app_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{12}
}

func (x *Metrics) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Metrics) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Metrics) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Tracing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	SampleRate    float64                `protobuf:"fixed64,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tracing) Reset() {
	*x = Tracing{}
	mi := &file_proto_app_v1_app_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tracing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracing) ProtoMessage() {}

func (x *Tracing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracing.ProtoReflect.Descriptor instead.
func (*Tracing) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{13}
}

func (x *Tracing) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Tracing) GetSampleRate() float64 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *Tracing) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Obs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logging       *Logging               `protobuf:"bytes,1,opt,name=logging,proto3" json:"logging,omitempty"`
	Metrics       *Metrics               `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Tracing       *Tracing               `protobuf:"bytes,3,opt,name=tracing,proto3" json:"tracing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Obs) Reset() {
	*x = Obs{}
	mi := &file_proto_app_v1_app_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Obs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Obs) ProtoMessage() {}

func (x *Obs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Obs.ProtoReflect.Descriptor instead.
func (*Obs) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{14}
}

func (x *Obs) GetLogging() *Logging {
	if x != nil {
		return x.Logging
	}
	return nil
}

func (x *Obs) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Obs) GetTracing() *Tracing {
	if x != nil {
		return x.Tracing
	}
	return nil
}

type DeployAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployAppResponse) Reset() {
	*x = DeployAppResponse{}
	mi := &file_proto_app_v1_app_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployAppResponse) ProtoMessage() {}

func (x *DeployAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployAppResponse.ProtoReflect.Descriptor instead.
func (*DeployAppResponse) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{15}
}

func (x *DeployAppResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Tail          int64                  `protobuf:"varint,2,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_proto_app_v1_app_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{16}
}

func (x *LogsRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *LogsRequest) GetTail() int64 {
	if x != nil {
		return x.Tail
	}
	return 0
}

type LogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PodName       string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Log           string                 `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	mi := &file_proto_app_v1_app_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{17}
}

func (x *LogsResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogsResponse) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *LogsResponse) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

// --- status ---
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_app_v1_app_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{18}
}

func (x *StatusRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type StatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Pods            int32                  `protobuf:"varint,2,opt,name=pods,proto3" json:"pods,omitempty"`
	CpuUsage        string                 `protobuf:"bytes,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage     string                 `protobuf:"bytes,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	Latency         string                 `protobuf:"bytes,5,opt,name=latency,proto3" json:"latency,omitempty"`
	Url             string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	DeployedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deployed_at,json=deployedAt,proto3" json:"deployed_at,omitempty"`
	DeployedBy      string                 `protobuf:"bytes,8,opt,name=deployed_by,json=deployedBy,proto3" json:"deployed_by,omitempty"`
	Tls             string                 `protobuf:"bytes,9,opt,name=tls,proto3" json:"tls,omitempty"`
	Health          string                 `protobuf:"bytes,10,opt,name=health,proto3" json:"health,omitempty"`
	Autoscaling     bool                   `protobuf:"varint,11,opt,name=autoscaling,proto3" json:"autoscaling,omitempty"`
	MinReplicas     int32                  `protobuf:"varint,12,opt,name=min_replicas,json=minReplicas,proto3" json:"min_replicas,omitempty"`
	MaxReplicas     int32                  `protobuf:"varint,13,opt,name=max_replicas,json=maxReplicas,proto3" json:"max_replicas,omitempty"`
	DesiredReplicas int32                  `protobuf:"varint,14,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`
	ReadyReplicas   int32                  `protobuf:"varint,15,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_app_v1_app_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_v1_app_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_app_v1_app_proto_rawDescGZIP(), []int{19}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetPods() int32 {
	if x != nil {
		return x.Pods
	}
	return 0
}

func (x *StatusResponse) GetCpuUsage() string {
	if x != nil {
		return x.CpuUsage
	}
	return ""
}

func (x *StatusResponse) GetMemoryUsage() string {
	if x != nil {
		return x.MemoryUsage
	}
	return ""
}

func (x *StatusResponse) GetLatency() string {
	if x != nil {
		return x.Latency
	}
	return ""
}

func (x *StatusResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *StatusResponse) GetDeployedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeployedAt
	}
	return nil
}

func (x *StatusResponse) GetDeployedBy() string {
	if x != nil {
		return x.DeployedBy
	}
	return ""
}

func (x *StatusResponse) GetTls() string {
	if x != nil {
		return x.Tls
	}
	return ""
}

func (x *StatusResponse) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *StatusResponse) GetAutoscaling() bool {
	if x != nil {
		return x.Autoscaling
	}
	return false
}

func (x *StatusResponse) GetMinReplicas() int32 {
	if x != nil {
		return x.MinReplicas
	}
	return 0
}

func (x *StatusResponse) GetMaxReplicas() int32 {
	if x != nil {
		return x.MaxReplicas
	}
	return 0
}

func (x *StatusResponse) GetDesiredReplicas() int32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

func (x *StatusResponse) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

var File_proto_app_v1_app_proto protoreflect.FileDescriptor

const file_proto_app_v1_app_proto_rawDesc = "" +
	"\n" +
	"\x16proto/app/v1/app.proto\x12\fproto.app.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa7\x01\n" +
	"\x10DeployAppRequest\x129\n" +
	"\vloco_config\x18\x01 \x01(\v2\x18.proto.app.v1.LocoConfigR\n" +
	"locoConfig\x12'\n" +
	"\x0fcontainer_image\x18\x02 \x01(\tR\x0econtainerImage\x12/\n" +
	"\benv_vars\x18\x03 \x03(\v2\x14.proto.app.v1.EnvVarR\aenvVars\"\xd0\x02\n" +
	"\n" +
	"LocoConfig\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.proto.app.v1.MetadataR\bmetadata\x125\n" +
	"\tresources\x18\x02 \x01(\v2\x17.proto.app.v1.ResourcesR\tresources\x12)\n" +
	"\x05build\x18\x03 \x01(\v2\x13.proto.app.v1.BuildR\x05build\x12/\n" +
	"\arouting\x18\x04 \x01(\v2\x15.proto.app.v1.RoutingR\arouting\x121\n" +
	"\x06health\x18\x05 \x01(\v2\x19.proto.app.v1.HealthCheckR\x06health\x12#\n" +
	"\x03env\x18\x06 \x01(\v2\x11.proto.app.v1.EnvR\x03env\x12#\n" +
	"\x03obs\x18\a \x01(\v2\x11.proto.app.v1.ObsR\x03obs\"g\n" +
	"\bMetadata\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\tR\rconfigVersion\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\".\n" +
	"\bReplicas\x12\x10\n" +
	"\x03max\x18\x01 \x01(\x05R\x03max\x12\x10\n" +
	"\x03min\x18\x02 \x01(\x05R\x03min\"g\n" +
	"\aScalers\x12\x1d\n" +
	"\n" +
	"cpu_target\x18\x01 \x01(\x05R\tcpuTarget\x12#\n" +
	"\rmemory_target\x18\x02 \x01(\x05R\fmemoryTarget\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\"\x9a\x01\n" +
	"\tResources\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\tR\x06memory\x122\n" +
	"\breplicas\x18\x03 \x01(\v2\x16.proto.app.v1.ReplicasR\breplicas\x12/\n" +
	"\ascalers\x18\x04 \x01(\v2\x15.proto.app.v1.ScalersR\ascalers\"D\n" +
	"\x05Build\x12'\n" +
	"\x0fdockerfile_path\x18\x01 \x01(\tR\x0edockerfilePath\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\x7f\n" +
	"\aRouting\x12!\n" +
	"\fidle_timeout\x18\x01 \x01(\x05R\vidleTimeout\x12\x1f\n" +
	"\vpath_prefix\x18\x02 \x01(\tR\n" +
	"pathPrefix\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1c\n" +
	"\tsubdomain\x18\x04 \x01(\tR\tsubdomain\"\xb0\x01\n" +
	"\vHealthCheck\x12\x1a\n" +
	"\binterval\x18\x01 \x01(\x05R\binterval\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x120\n" +
	"\x14startup_grace_period\x18\x03 \x01(\x05R\x12startupGracePeriod\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x05R\atimeout\x12%\n" +
	"\x0efail_threshold\x18\x05 \x01(\x05R\rfailThreshold\"M\n" +
	"\x03Env\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x122\n" +
	"\tvariables\x18\x02 \x03(\v2\x14.proto.app.v1.EnvVarR\tvariables\"2\n" +
	"\x06EnvVar\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"n\n" +
	"\aLogging\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12)\n" +
	"\x10retention_period\x18\x02 \x01(\tR\x0fretentionPeriod\x12\x1e\n" +
	"\n" +
	"structured\x18\x03 \x01(\bR\n" +
	"structured\"K\n" +
	"\aMetrics\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"\xb2\x01\n" +
	"\aTracing\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x01R\n" +
	"sampleRate\x123\n" +
	"\x04tags\x18\x03 \x03(\v2\x1f.proto.app.v1.Tracing.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\x01\n" +
	"\x03Obs\x12/\n" +
	"\alogging\x18\x01 \x01(\v2\x15.proto.app.v1.LoggingR\alogging\x12/\n" +
	"\ametrics\x18\x02 \x01(\v2\x15.proto.app.v1.MetricsR\ametrics\x12/\n" +
	"\atracing\x18\x03 \x01(\v2\x15.proto.app.v1.TracingR\atracing\"-\n" +
	"\x11DeployAppResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"<\n" +
	"\vLogsRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x12\n" +
	"\x04tail\x18\x02 \x01(\x03R\x04tail\"u\n" +
	"\fLogsResponse\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x10\n" +
	"\x03log\x18\x03 \x01(\tR\x03log\"*\n" +
	"\rStatusRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\"\xea\x03\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04pods\x18\x02 \x01(\x05R\x04pods\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\tR\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x04 \x01(\tR\vmemoryUsage\x12\x18\n" +
	"\alatency\x18\x05 \x01(\tR\alatency\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12;\n" +
	"\vdeployed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deployedAt\x12\x1f\n" +
	"\vdeployed_by\x18\b \x01(\tR\n" +
	"deployedBy\x12\x10\n" +
	"\x03tls\x18\t \x01(\tR\x03tls\x12\x16\n" +
	"\x06health\x18\n" +
	" \x01(\tR\x06health\x12 \n" +
	"\vautoscaling\x18\v \x01(\bR\vautoscaling\x12!\n" +
	"\fmin_replicas\x18\f \x01(\x05R\vminReplicas\x12!\n" +
	"\fmax_replicas\x18\r \x01(\x05R\vmaxReplicas\x12)\n" +
	"\x10desired_replicas\x18\x0e \x01(\x05R\x0fdesiredReplicas\x12%\n" +
	"\x0eready_replicas\x18\x0f \x01(\x05R\rreadyReplicas2\xe6\x01\n" +
	"\n" +
	"AppService\x12N\n" +
	"\tDeployApp\x12\x1e.proto.app.v1.DeployAppRequest\x1a\x1f.proto.app.v1.DeployAppResponse\"\x00\x12A\n" +
	"\x04Logs\x12\x19.proto.app.v1.LogsRequest\x1a\x1a.proto.app.v1.LogsResponse\"\x000\x01\x12E\n" +
	"\x06Status\x12\x1b.proto.app.v1.StatusRequest\x1a\x1c.proto.app.v1.StatusResponse\"\x00B0Z.github.com/nikumar1206/loco/proto/app/v1;appv1b\x06proto3"

var (
	file_proto_app_v1_app_proto_rawDescOnce sync.Once
	file_proto_app_v1_app_proto_rawDescData []byte
)

func file_proto_app_v1_app_proto_rawDescGZIP() []byte {
	file_proto_app_v1_app_proto_rawDescOnce.Do(func() {
		file_proto_app_v1_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_app_v1_app_proto_rawDesc), len(file_proto_app_v1_app_proto_rawDesc)))
	})
	return file_proto_app_v1_app_proto_rawDescData
}

var file_proto_app_v1_app_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_app_v1_app_proto_goTypes = []any{
	(*DeployAppRequest)(nil),      // 0: proto.app.v1.DeployAppRequest
	(*LocoConfig)(nil),            // 1: proto.app.v1.LocoConfig
	(*Metadata)(nil),              // 2: proto.app.v1.Metadata
	(*Replicas)(nil),              // 3: proto.app.v1.Replicas
	(*Scalers)(nil),               // 4: proto.app.v1.Scalers
	(*Resources)(nil),             // 5: proto.app.v1.Resources
	(*Build)(nil),                 // 6: proto.app.v1.Build
	(*Routing)(nil),               // 7: proto.app.v1.Routing
	(*HealthCheck)(nil),           // 8: proto.app.v1.HealthCheck
	(*Env)(nil),                   // 9: proto.app.v1.Env
	(*EnvVar)(nil),                // 10: proto.app.v1.EnvVar
	(*Logging)(nil),               // 11: proto.app.v1.Logging
	(*Metrics)(nil),               // 12: proto.app.v1.Metrics
	(*Tracing)(nil),               // 13: proto.app.v1.Tracing
	(*Obs)(nil),                   // 14: proto.app.v1.Obs
	(*DeployAppResponse)(nil),     // 15: proto.app.v1.DeployAppResponse
	(*LogsRequest)(nil),           // 16: proto.app.v1.LogsRequest
	(*LogsResponse)(nil),          // 17: proto.app.v1.LogsResponse
	(*StatusRequest)(nil),         // 18: proto.app.v1.StatusRequest
	(*StatusResponse)(nil),        // 19: proto.app.v1.StatusResponse
	nil,                           // 20: proto.app.v1.Tracing.TagsEntry
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
}
var file_proto_app_v1_app_proto_depIdxs = []int32{
	1,  // 0: proto.app.v1.DeployAppRequest.loco_config:type_name -> proto.app.v1.LocoConfig
	10, // 1: proto.app.v1.DeployAppRequest.env_vars:type_name -> proto.app.v1.EnvVar
	2,  // 2: proto.app.v1.LocoConfig.metadata:type_name -> proto.app.v1.Metadata
	5,  // 3: proto.app.v1.LocoConfig.resources:type_name -> proto.app.v1.Resources
	6,  // 4: proto.app.v1.LocoConfig.build:type_name -> proto.app.v1.Build
	7,  // 5: proto.app.v1.LocoConfig.routing:type_name -> proto.app.v1.Routing
	8,  // 6: proto.app.v1.LocoConfig.health:type_name -> proto.app.v1.HealthCheck
	9,  // 7: proto.app.v1.LocoConfig.env:type_name -> proto.app.v1.Env
	14, // 8: proto.app.v1.LocoConfig.obs:type_name -> proto.app.v1.Obs
	3,  // 9: proto.app.v1.Resources.replicas:type_name -> proto.app.v1.Replicas
	4,  // 10: proto.app.v1.Resources.scalers:type_name -> proto.app.v1.Scalers
	10, // 11: proto.app.v1.Env.variables:type_name -> proto.app.v1.EnvVar
	20, // 12: proto.app.v1.Tracing.tags:type_name -> proto.app.v1.Tracing.TagsEntry
	11, // 13: proto.app.v1.Obs.logging:type_name -> proto.app.v1.Logging
	12, // 14: proto.app.v1.Obs.metrics:type_name -> proto.app.v1.Metrics
	13, // 15: proto.app.v1.Obs.tracing:type_name -> proto.app.v1.Tracing
	21, // 16: proto.app.v1.LogsResponse.timestamp:type_name -> google.protobuf.Timestamp
	21, // 17: proto.app.v1.StatusResponse.deployed_at:type_name -> google.protobuf.Timestamp
	0,  // 18: proto.app.v1.AppService.DeployApp:input_type -> proto.app.v1.DeployAppRequest
	16, // 19: proto.app.v1.AppService.Logs:input_type -> proto.app.v1.LogsRequest
	18, // 20: proto.app.v1.AppService.Status:input_type -> proto.app.v1.StatusRequest
	15, // 21: proto.app.v1.AppService.DeployApp:output_type -> proto.app.v1.DeployAppResponse
	17, // 22: proto.app.v1.AppService.Logs:output_type -> proto.app.v1.LogsResponse
	19, // 23: proto.app.v1.AppService.Status:output_type -> proto.app.v1.StatusResponse
	21, // [21:24] is the sub-list for method output_type
	18, // [18:21] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_app_v1_app_proto_init() }
func file_proto_app_v1_app_proto_init() {
	if File_proto_app_v1_app_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_app_v1_app_proto_rawDesc), len(file_proto_app_v1_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_app_v1_app_proto_goTypes,
		DependencyIndexes: file_proto_app_v1_app_proto_depIdxs,
		MessageInfos:      file_proto_app_v1_app_proto_msgTypes,
	}.Build()
	File_proto_app_v1_app_proto = out.File
	file_proto_app_v1_app_proto_goTypes = nil
	file_proto_app_v1_app_proto_depIdxs = nil
}
