// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: proto/oauth/v1/oauth.proto

package oauthv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GithubOAuthDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubOAuthDetailsRequest) Reset() {
	*x = GithubOAuthDetailsRequest{}
	mi := &file_proto_oauth_v1_oauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubOAuthDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubOAuthDetailsRequest) ProtoMessage() {}

func (x *GithubOAuthDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oauth_v1_oauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubOAuthDetailsRequest.ProtoReflect.Descriptor instead.
func (*GithubOAuthDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_oauth_v1_oauth_proto_rawDescGZIP(), []int{0}
}

type GithubOAuthDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	TokenTtl      float64                `protobuf:"fixed64,2,opt,name=token_ttl,json=tokenTtl,proto3" json:"token_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubOAuthDetailsResponse) Reset() {
	*x = GithubOAuthDetailsResponse{}
	mi := &file_proto_oauth_v1_oauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubOAuthDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubOAuthDetailsResponse) ProtoMessage() {}

func (x *GithubOAuthDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oauth_v1_oauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubOAuthDetailsResponse.ProtoReflect.Descriptor instead.
func (*GithubOAuthDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_oauth_v1_oauth_proto_rawDescGZIP(), []int{1}
}

func (x *GithubOAuthDetailsResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GithubOAuthDetailsResponse) GetTokenTtl() float64 {
	if x != nil {
		return x.TokenTtl
	}
	return 0
}

var File_proto_oauth_v1_oauth_proto protoreflect.FileDescriptor

const file_proto_oauth_v1_oauth_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/oauth/v1/oauth.proto\x12\x0eproto.oauth.v1\"\x1b\n" +
	"\x19GithubOAuthDetailsRequest\"V\n" +
	"\x1aGithubOAuthDetailsResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1b\n" +
	"\ttoken_ttl\x18\x02 \x01(\x01R\btokenTtl2}\n" +
	"\fOAuthService\x12m\n" +
	"\x12GithubOAuthDetails\x12).proto.oauth.v1.GithubOAuthDetailsRequest\x1a*.proto.oauth.v1.GithubOAuthDetailsResponse\"\x00B4Z2github.com/nikumar1206/loco/proto/oauth/v1;oauthv1b\x06proto3"

var (
	file_proto_oauth_v1_oauth_proto_rawDescOnce sync.Once
	file_proto_oauth_v1_oauth_proto_rawDescData []byte
)

func file_proto_oauth_v1_oauth_proto_rawDescGZIP() []byte {
	file_proto_oauth_v1_oauth_proto_rawDescOnce.Do(func() {
		file_proto_oauth_v1_oauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_oauth_v1_oauth_proto_rawDesc), len(file_proto_oauth_v1_oauth_proto_rawDesc)))
	})
	return file_proto_oauth_v1_oauth_proto_rawDescData
}

var file_proto_oauth_v1_oauth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_oauth_v1_oauth_proto_goTypes = []any{
	(*GithubOAuthDetailsRequest)(nil),  // 0: proto.oauth.v1.GithubOAuthDetailsRequest
	(*GithubOAuthDetailsResponse)(nil), // 1: proto.oauth.v1.GithubOAuthDetailsResponse
}
var file_proto_oauth_v1_oauth_proto_depIdxs = []int32{
	0, // 0: proto.oauth.v1.OAuthService.GithubOAuthDetails:input_type -> proto.oauth.v1.GithubOAuthDetailsRequest
	1, // 1: proto.oauth.v1.OAuthService.GithubOAuthDetails:output_type -> proto.oauth.v1.GithubOAuthDetailsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_oauth_v1_oauth_proto_init() }
func file_proto_oauth_v1_oauth_proto_init() {
	if File_proto_oauth_v1_oauth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_oauth_v1_oauth_proto_rawDesc), len(file_proto_oauth_v1_oauth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_oauth_v1_oauth_proto_goTypes,
		DependencyIndexes: file_proto_oauth_v1_oauth_proto_depIdxs,
		MessageInfos:      file_proto_oauth_v1_oauth_proto_msgTypes,
	}.Build()
	File_proto_oauth_v1_oauth_proto = out.File
	file_proto_oauth_v1_oauth_proto_goTypes = nil
	file_proto_oauth_v1_oauth_proto_depIdxs = nil
}
