name: Deploy and Update Infra
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Decode OIDC token claims
        run: |
          ID_TOKEN=$(echo "${ACTIONS_ID_TOKEN}")
          echo "$ID_TOKEN" | cut -d "." -f2 | base64 -d | jq .
        env:
          ACTIONS_ID_TOKEN: ${{ steps.get_token.outputs.id_token }}

      - name: Configure AWS Credentials from GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::094594576609:role/assumable-tfe-role
          aws-region: us-east-2

      - name: Terraform Plan
        run: terraform plan
