name: Deploy and Update Infra
on:
  push:
    branches:
      - main
env:
  # TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: cd terraform && terraform init

      - name: Terraform Plan
        run: cd terraform && terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
