name: Deploy and Update Infra

on:
    push:
        branches:
            - main

env:
    TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
    DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_PAT }}

jobs:
    infra:
        name: Provision Infrastructure
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              run: cd terraform && terraform init

            - name: Terraform Plan
              run: cd terraform && terraform plan -out=tfplan

            - name: Terraform Apply
              run: cd terraform && terraform apply -auto-approve "tfplan"

    deploy:
        name: Deploy Manifests to Cluster
        runs-on: ubuntu-latest
        needs: infra
        environment: production
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            # Optional: Set up DigitalOcean CLI or extract kubeconfig from Terraform outputs
            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_PAT }}

            - name: Get kubeconfig
              run: doctl kubernetes cluster kubeconfig save loco-cluster

            - name: Verify cluster access
              run: kubectl get nodes

            - name: Wait for nodes to be ready
              run: kubectl wait --for=condition=Ready node --all --timeout=180s

            - name: Apply app manifests
              run: |
                  kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml
                  kubectl apply -f https://github.com/envoyproxy/gateway/releases/download/v1.4.1/envoy-gateway-crds.yaml

            - name: Create namespace if needed
              run: |
                  kubectl apply -f ./kube/loco_namespace.yml
                  kubectl apply -f ./kube/gateway.yml
                  kubectl apply -f ./kube/gateway_route.yml
                  kubectl apply -f ./kube/app_deployment.yml
